# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [7]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [8]:
#my sol
import numpy as np

#sol
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
#my sol
print(np.__version__)
np.show_config()

#sol
answer(2)

2.3.1
{
  "Compilers": {
    "c": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.1.2",
      "commands": "cython"
    },
    "c++": {
      "name": "gcc",
      "linker": "ld.bfd",
      "version": "14.2.1",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "linux"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.29",
      "detection method": "pkgconfig",
      "include directory": "/opt/_internal/cpython-3.12.10/lib/python3.12/site-packages/scipy_openblas64/include",
      "lib directory": "/opt/_internal/cpython-3.12.10/lib/python3

/home/arnav-gr0ver/DEV/Research/Mechanistic-Interpretability/np-100/venv/lib/python3.12/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
#my sol
vec = np.zeros(10)
print(vec)

#sol
answer(3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [11]:
#my sol
Z = np.ones((5, 5))
print(Z.size * Z.itemsize)

#sol
answer(4)

200
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
#my sol
help(np.add) #oop not exactly from command line

#sol 
answer(5)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
#my sol
V = np.zeros(10)
V[4] = 1
print(V)

#sol
answer(6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
V = np.arange(10, 50) #inclusive
print(V)

#sol
answer(7)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Z = np.arange(10,50)
print(Z)


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [15]:
V = np.arange(1, 10)
np.flip(V)
print(V)

#sol
answer(8)

[1 2 3 4 5 6 7 8 9]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
V = np.arange(0,9).reshape(3,3)
print(V)

#sol
answer(9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [17]:
V = np.array([1,2,0,0,4,0])
print(V.nonzero())

#sol
answer(10)

(array([0, 1, 4]),)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [23]:
M = np.zeros((3,3))
M[0,0] = 1
M[1,1] = 1
M[2,2]= 1
print(M)

#sol
answer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [31]:
M = np.random.rand(3,3,3)
print(M)

#sol
answer(12)

[[[0.6452391  0.55563963 0.19045044]
  [0.01965197 0.55871816 0.11998844]
  [0.42929161 0.49164661 0.05960395]]

 [[0.34615507 0.1089444  0.40491113]
  [0.8582029  0.48978304 0.14142439]
  [0.04780468 0.90543379 0.16803051]]

 [[0.55434086 0.31706803 0.53562578]
  [0.43199648 0.71884797 0.05648344]
  [0.1291511  0.59273114 0.88156078]]]
Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [35]:
M = np.random.random((10,10))
print(M)
print(M.min())
print(M.max())

#sol
answer(13)

[[0.90056566 0.97928508 0.47703968 0.90743245 0.25118749 0.51320161
  0.50578887 0.93450506 0.06648798 0.87810622]
 [0.39158336 0.13876261 0.07814786 0.36048289 0.12838811 0.32387889
  0.34107817 0.96484423 0.47671508 0.60948131]
 [0.47569915 0.60454704 0.54526428 0.02796623 0.0951972  0.26369395
  0.46188688 0.25534563 0.86896643 0.79281624]
 [0.40354214 0.48287855 0.10333284 0.07744027 0.61935067 0.39170236
  0.54529415 0.14578763 0.21046832 0.06547568]
 [0.40734521 0.68812745 0.35288809 0.65161937 0.72479447 0.05995763
  0.75804822 0.97833984 0.94896291 0.05047826]
 [0.24744092 0.7703981  0.65422996 0.58103594 0.59118268 0.96823375
  0.41026359 0.15152434 0.28827053 0.22913294]
 [0.62218666 0.34553244 0.9367036  0.36130083 0.37140443 0.10780159
  0.89143971 0.41424319 0.69911719 0.46456131]
 [0.30678202 0.36243685 0.07584969 0.82537773 0.4933306  0.19828956
  0.02250476 0.976484   0.82560154 0.72252681]
 [0.90957175 0.93589094 0.83544137 0.60618915 0.31467319 0.69395021
  0.42296968

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [38]:
V = np.random.random(30)
print(V)
print(V.mean())

#sol
answer(14)

[0.76504514 0.22953234 0.36606975 0.62257472 0.32816927 0.30392815
 0.19717203 0.98888524 0.42482494 0.29446901 0.13070007 0.48145041
 0.02680754 0.04146802 0.44610945 0.17801233 0.20607181 0.25275474
 0.67253036 0.56294237 0.36055862 0.31108596 0.55522319 0.14080591
 0.8754838  0.72456626 0.35399188 0.93182351 0.01691793 0.8278734 ]
0.4205949387372601
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [44]:
V = np.zeros((10,10))
V[0, :] = 1
V[9, :] = 1
V[:, 0] = 1
V[:, 9] = 1
print(V)

#sol
answer(15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [49]:
M = np.ones((3,3))
M = np.pad(M, pad_width=1, mode='constant', constant_values=0)
print(M)

#sol
answer(16)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [57]:
#false

#sol
answer(17)

print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [63]:
#STILL DOING THIS
M = np.zeros((5,5))
np.fill_diagonal(M, 1)
np.tril(M, k=-1)
print(M)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)